truncate -s 0 "./500px/Privacy Policy.html"
truncate -s 0 "./500px/Terms of Service.html"
truncate -s 0 "./Allrecipes/Privacy Policy.html"
truncate -s 0 "./Allrecipes/Terms of Service.html"
truncate -s 0 "./Amazon/Privacy Policy.html"
truncate -s 0 "./Amazon/Terms of Service.html"
truncate -s 0 "./Amazon/unknown.html"
truncate -s 0 "./AmazonAds/unknown.html"
truncate -s 0 "./AmazonAlexa/Terms of Service.html"
truncate -s 0 "./AmazonAmazonAppStoreAndroid/Terms of Service.html"
truncate -s 0 "./AmazonAppSuite/Legal Information.html"
truncate -s 0 "./AmazonCoins/Terms of Service.html"
truncate -s 0 "./AmazonDevice/Terms of Service.html"
truncate -s 0 "./AmazonDriveAndPrimePhotos/Terms of Service.html"
truncate -s 0 "./AmazonFreeTimeUnlimited/Terms of Service.html"
truncate -s 0 "./AmazonGameCircle/Terms of Service.html"
truncate -s 0 "./AmazonKindleAndroid/Legal Information.html"
truncate -s 0 "./AmazonKindleCloudReader/Legal Information.html"
truncate -s 0 "./AmazonKindleDistributor/Terms of Service.html"
truncate -s 0 "./AmazonKindleMac/Legal Information.html"
truncate -s 0 "./AmazonKindleNotifications/Terms of Service.html"
truncate -s 0 "./AmazonKindlePC/Legal Information.html"
truncate -s 0 "./AmazonKindleStore/Terms of Service.html"
truncate -s 0 "./AmazonKindleTable/Terms of Service.html"
truncate -s 0 "./AmazonKindleUnlimited/Terms of Service.html"
truncate -s 0 "./AmazonKindleWindows/Legal Information.html"
truncate -s 0 "./AmazonMaps/Terms of Service.html"
truncate -s 0 "./AmazonMonthlyPayments/Terms of Service.html"
truncate -s 0 "./AmazonMusic/Terms of Service.html"
truncate -s 0 "./AmazonOffers/Terms of Service.html"
truncate -s 0 "./AmazonPrime/Terms of Service.html"
truncate -s 0 "./AmazonSilk/Terms of Service.html"
truncate -s 0 "./Android/Privacy Policy.html"
truncate -s 0 "./App/Privacy Policy.html"
truncate -s 0 "./App/Terms of Service.html"
truncate -s 0 "./Apple/Privacy Policy.html"
truncate -s 0 "./Apple/Terms of Service.html"
truncate -s 0 "./AppleGameCenter/Terms of Service.html"
truncate -s 0 "./AppleIChat/Terms of Service.html"
truncate -s 0 "./AppleICloud/Terms of Service.html"
truncate -s 0 "./AppleITunes/Terms of Service.html"
truncate -s 0 "./AppleSupportCommunities/Terms of Service.html"
truncate -s 0 "./Att/Privacy Policy.html"
truncate -s 0 "./Att/Terms of Service.html"
truncate -s 0 "./AttWireless/unknown.html"
truncate -s 0 "./Bbc/Privacy Policy.html"
truncate -s 0 "./Bbc/Terms of Service.html"
truncate -s 0 "./Bearshare/Privacy Policy.html"
truncate -s 0 "./Bearshare/Terms of Service.html"
truncate -s 0 "./Bit/Privacy Policy.html"
truncate -s 0 "./Bit/Terms of Service.html"
truncate -s 0 "./Blizzard/Privacy Policy.html"
truncate -s 0 "./Blizzard/Terms of Service.html"
truncate -s 0 "./Blogger/Privacy Policy.html"
truncate -s 0 "./Blogger/Terms of Service.html"
truncate -s 0 "./Blogspot/Privacy Policy.html"
truncate -s 0 "./Blogspot/Terms of Service.html"
truncate -s 0 "./Cloudant/Privacy Policy.html"
truncate -s 0 "./Cloudant/Terms of Service.html"
truncate -s 0 "./Cnet/Privacy Policy.html"
truncate -s 0 "./Cnn/Privacy Policy.html"
truncate -s 0 "./Cnn/Terms of Service.html"
truncate -s 0 "./Couchsurfing/Privacy Policy.html"
truncate -s 0 "./Couchsurfing/Terms of Service.html"
truncate -s 0 "./Coursera/Privacy Policy.html"
truncate -s 0 "./Coursera/Terms of Service.html"
truncate -s 0 "./Coursera/unknown.html"
truncate -s 0 "./Del/Privacy Policy.html"
truncate -s 0 "./Del/Terms of Service.html"
truncate -s 0 "./Dictionary/Terms of Service.html"
truncate -s 0 "./Discordapp/Terms of Service.html"
truncate -s 0 "./Disqus/Privacy Policy.html"
truncate -s 0 "./Disqus/Terms of Service.html"
truncate -s 0 "./Dropbox/Privacy Policy.html"
truncate -s 0 "./Duckduckgo/Privacy Policy.html"
truncate -s 0 "./Ebuddy/Privacy Policy.html"
truncate -s 0 "./Ebuddy/Terms of Service.html"
truncate -s 0 "./Envato/Privacy Policy.html"
truncate -s 0 "./Evernote/Privacy Policy.html"
truncate -s 0 "./Evernote/Terms of Service.html"
truncate -s 0 "./Facebook/Privacy Policy.html"
truncate -s 0 "./Facebook/Terms of Service.html"
truncate -s 0 "./Finance/Privacy Policy.html"
truncate -s 0 "./Flattr/Privacy Policy.html"
truncate -s 0 "./Flattr/Terms of Service.html"
truncate -s 0 "./Flickr/Community Guidelines.html"
truncate -s 0 "./Flickr/Privacy Policy.html"
truncate -s 0 "./Flickr/Terms of Service.html"
truncate -s 0 "./Forums/Terms of Service.html"
truncate -s 0 "./Foursquare/Privacy Policy.html"
truncate -s 0 "./Foursquare/Terms of Service.html"
truncate -s 0 "./Foxnews/Closed Captioning Policy.html"
truncate -s 0 "./Foxnews/Privacy Policy.html"
truncate -s 0 "./Foxnews/Terms of Service.html"
truncate -s 0 "./Freeforums/Privacy Policy.html"
truncate -s 0 "./Github/Privacy Policy.html"
truncate -s 0 "./Github/Terms of Service.html"
truncate -s 0 "./Gmail/Privacy Policy.html"
truncate -s 0 "./Google/Privacy Policy.html"
truncate -s 0 "./Google/Terms of Service.html"
truncate -s 0 "./Grammarly/Privacy Policy.html"
truncate -s 0 "./Grammarly/Terms of Service.html"
truncate -s 0 "./Gravatar/Privacy Policy.html"
truncate -s 0 "./Habbo/Privacy Policy.html"
truncate -s 0 "./Habbo/Terms of Service.html"
truncate -s 0 "./Hypster/Privacy Policy.html"
truncate -s 0 "./Hypster/Terms of Service.html"
truncate -s 0 "./Identi/Privacy Policy.html"
truncate -s 0 "./Identi/Terms of Service.html"
truncate -s 0 "./Ifttt/Privacy Policy.html"
truncate -s 0 "./Ifttt/Terms of Service.html"
truncate -s 0 "./Imgur/Privacy Policy.html"
truncate -s 0 "./Imgur/Terms of Service.html"
truncate -s 0 "./Instagr/Privacy Policy.html"
truncate -s 0 "./Instagram/Privacy Policy.html"
truncate -s 0 "./Instagram/Terms of Service.html"
truncate -s 0 "./Lastpass/Privacy Policy.html"
truncate -s 0 "./Lastpass/Terms of Service.html"
truncate -s 0 "./Linkedin/Privacy Policy.html"
truncate -s 0 "./Linkedin/Terms of Service.html"
truncate -s 0 "./Live/Privacy Policy.html"
truncate -s 0 "./Live/Terms of Service.html"
truncate -s 0 "./Market/Terms of Service.html"
truncate -s 0 "./Microsoft/Privacy Policy.html"
truncate -s 0 "./Microsoft/Terms of Service.html"
truncate -s 0 "./Microsoftstore/Privacy Policy.html"
truncate -s 0 "./Microsoftstore/Terms of Service.html"
truncate -s 0 "./Minecraft/Terms of Service.html"
truncate -s 0 "./Msn/Privacy Policy.html"
truncate -s 0 "./Msn/Terms of Service.html"
truncate -s 0 "./Myspace/Privacy Policy.html"
truncate -s 0 "./Myspace/Terms of Service.html"
truncate -s 0 "./Nabble/Privacy Policy.html"
truncate -s 0 "./Nabble/Terms of Service.html"
truncate -s 0 "./Netflix/Privacy Policy.html"
truncate -s 0 "./Netflix/Terms of Service.html"
truncate -s 0 "./Olx/Terms of Service.html"
truncate -s 0 "./Owncube/Privacy Policy.html"
truncate -s 0 "./Owncube/Terms of Service.html"
truncate -s 0 "./Packagetrackr/Privacy Policy.html"
truncate -s 0 "./Packagetrackr/Terms of Service.html"
truncate -s 0 "./Phpbb/Privacy Policy.html"
truncate -s 0 "./Phpbb/Terms of Service.html"
truncate -s 0 "./Play/Terms of Service.html"
truncate -s 0 "./Plus/Privacy Policy.html"
truncate -s 0 "./Quora/Privacy Policy.html"
truncate -s 0 "./Quora/Terms of Service.html"
truncate -s 0 "./Rapidshare/Privacy Policy.html"
truncate -s 0 "./Rapidshare/Terms of Service.html"
truncate -s 0 "./Researchgate/Copyright Claims Policy.html"
truncate -s 0 "./Researchgate/Privacy Policy.html"
truncate -s 0 "./Researchgate/Terms of Service.html"
truncate -s 0 "./Runescape/Privacy Policy.html"
truncate -s 0 "./Runescape/Terms of Service.html"
truncate -s 0 "./Seenthis/Copyright Claims Policy.html"
truncate -s 0 "./Signal/Terms of Service.html"
truncate -s 0 "./Skype/Privacy Policy.html"
truncate -s 0 "./Skype/Terms of Service.html"
truncate -s 0 "./Skype/unknown.html"
truncate -s 0 "./SkypeGroupVideoCalling/unknown.html"
truncate -s 0 "./Sonic/Terms of Service.html"
truncate -s 0 "./Soundcloud/Privacy Policy.html"
truncate -s 0 "./Soundcloud/Terms of Service.html"
truncate -s 0 "./Spideroak/Privacy Policy.html"
truncate -s 0 "./Spideroak/Terms of Service.html"
truncate -s 0 "./Spotify/Privacy Policy.html"
truncate -s 0 "./Spotify/Terms of Service.html"
truncate -s 0 "./SpotifyMobile/Terms of Service.html"
truncate -s 0 "./SpotifyPremium/Terms of Service.html"
truncate -s 0 "./SpotifyUnlimited/Terms of Service.html"
truncate -s 0 "./Steampowered/Legal Information.html"
truncate -s 0 "./Steampowered/Privacy Policy.html"
truncate -s 0 "./Steampowered/unknown.html"
truncate -s 0 "./Trello/Privacy Policy.html"
truncate -s 0 "./Trello/Terms of Service.html"
truncate -s 0 "./Trello/unknown.html"
truncate -s 0 "./Tumblr/Privacy Policy.html"
truncate -s 0 "./Tumblr/Terms of Service.html"
truncate -s 0 "./Twitpic/Privacy Policy.html"
truncate -s 0 "./Twitpic/Terms of Service.html"
truncate -s 0 "./Twitter/Privacy Policy.html"
truncate -s 0 "./Twitter/Terms of Service.html"
truncate -s 0 "./Vbulletin/Privacy Policy.html"
truncate -s 0 "./Vbulletin/Terms of Service.html"
truncate -s 0 "./Verizon/Privacy Policy.html"
truncate -s 0 "./Verizon/Terms of Service.html"
truncate -s 0 "./Videobb/Privacy Policy.html"
truncate -s 0 "./Videobb/Terms of Service.html"
truncate -s 0 "./W3schools/Privacy Policy.html"
truncate -s 0 "./W3schools/Terms of Service.html"
truncate -s 0 "./Whatsapp/Terms of Service.html"
truncate -s 0 "./Whatsapp/unknown.html"
truncate -s 0 "./Wikimediafoundation/Privacy Policy.html"
truncate -s 0 "./Wikimediafoundation/Terms of Service.html"
truncate -s 0 "./Wikipedia/Privacy Policy.html"
truncate -s 0 "./Wikipedia/Terms of Service.html"
truncate -s 0 "./Wordfeud/Privacy Policy.html"
truncate -s 0 "./Wordfeud/Terms of Service.html"
truncate -s 0 "./Wordpress/Privacy Policy.html"
truncate -s 0 "./Wordpress/Terms of Service.html"
truncate -s 0 "./Xfinity/Privacy Policy.html"
truncate -s 0 "./Xfinity/Terms of Service.html"
truncate -s 0 "./XfinityResidentialSubscription/Terms of Service.html"
truncate -s 0 "./XfinityWebServices/Privacy Policy.html"
truncate -s 0 "./XfinityWebServices/Terms of Service.html"
truncate -s 0 "./Xfire/Privacy Policy.html"
truncate -s 0 "./Xfire/Terms of Service.html"
truncate -s 0 "./Xing/Privacy Policy.html"
truncate -s 0 "./Xing/Terms of Service.html"
truncate -s 0 "./Yahoo/Privacy Policy.html"
truncate -s 0 "./Yahoo/Terms of Service.html"
truncate -s 0 "./Youtube/Privacy Policy.html"
truncate -s 0 "./Youtube/Terms of Service.html"
truncate -s 0 "./Zoosk/Privacy Policy.html"
